apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: app-data-backups
  namespace: longhorn-system
spec:
  name: app-data-backups
  task: backup
  cron: "0 20 * * 2,4,7"
  retain: 100
  concurrency: 1
  groups:
    - apps
